/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1;

import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author Vicente193373
 */
public class VNT_Singup extends javax.swing.JFrame {

    //Se necesita definir una variable File para contener la foto de perfil
    File im;
    
    public VNT_Singup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FLD_Nombre = new javax.swing.JPasswordField();
        FLD_Email = new javax.swing.JTextField();
        BTN_Crear = new javax.swing.JButton();
        TXT_Email = new javax.swing.JLabel();
        TXT_Nombre = new javax.swing.JLabel();
        FLD_Password1 = new javax.swing.JPasswordField();
        TXT_Password1 = new javax.swing.JLabel();
        FLD_Password2 = new javax.swing.JPasswordField();
        TXT_Password2 = new javax.swing.JLabel();
        FLD_Tel = new javax.swing.JTextField();
        TXT_Tel = new javax.swing.JLabel();
        TXT_FechaN = new javax.swing.JLabel();
        SPN_Dia = new javax.swing.JSpinner();
        SPN_Mes = new javax.swing.JSpinner();
        SPN_Anio = new javax.swing.JSpinner();
        BTN_Foto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BTN_Crear.setText("Crear Cuenta");
        BTN_Crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_CrearActionPerformed(evt);
            }
        });

        TXT_Email.setText("Email");

        TXT_Nombre.setText("Nombre");

        TXT_Password1.setText("Contraseña");

        TXT_Password2.setText("Repetir Contraseña");

        TXT_Tel.setText("Telefono");

        TXT_FechaN.setText("Fecha de Nacimiento");

        SPN_Dia.setModel(new javax.swing.SpinnerNumberModel(1, 1, 30, 1));

        SPN_Mes.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));

        SPN_Anio.setModel(new javax.swing.SpinnerNumberModel(2025, 1500, 3000, 1));

        BTN_Foto.setText("Foto");
        BTN_Foto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_FotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(424, 424, 424)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SPN_Anio, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(SPN_Dia, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(1, 1, 1)
                            .addComponent(SPN_Mes, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TXT_FechaN, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TXT_Tel, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FLD_Tel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(TXT_Password2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(FLD_Password2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TXT_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(FLD_Nombre)
                                    .addComponent(BTN_Crear, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TXT_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FLD_Email, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TXT_Password1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FLD_Password1))))))
                .addGap(424, 424, 424))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BTN_Foto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(469, 469, 469))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(BTN_Foto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TXT_Email)
                .addGap(1, 1, 1)
                .addComponent(FLD_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(TXT_Tel)
                .addGap(1, 1, 1)
                .addComponent(FLD_Tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(TXT_Nombre)
                .addGap(1, 1, 1)
                .addComponent(FLD_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TXT_FechaN)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SPN_Dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SPN_Mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SPN_Anio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(TXT_Password1)
                .addGap(1, 1, 1)
                .addComponent(FLD_Password1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(TXT_Password2)
                .addGap(1, 1, 1)
                .addComponent(FLD_Password2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 30, Short.MAX_VALUE)
                .addComponent(BTN_Crear)
                .addGap(25, 25, 25))
        );

        FLD_Nombre.getAccessibleContext().setAccessibleName("ID_FLD_Password");
        FLD_Email.getAccessibleContext().setAccessibleName("ID_FLD_Identif");
        FLD_Email.getAccessibleContext().setAccessibleDescription("");
        BTN_Crear.getAccessibleContext().setAccessibleName("ID_BTN_Crear");
        TXT_Email.getAccessibleContext().setAccessibleName("ID_TXT_Identif");
        TXT_Email.getAccessibleContext().setAccessibleDescription("");
        TXT_Nombre.getAccessibleContext().setAccessibleName("ID_TXT_Password");
        TXT_FechaN.getAccessibleContext().setAccessibleName("ID_TXT_FechaN");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_FotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_FotoActionPerformed
        // TODO add your handling code here:
        
        //Se debe definir para usar la ventanilla que busca un archivo
        JFileChooser archivo = new JFileChooser();
        archivo.showOpenDialog(this);
        this.im = archivo.getSelectedFile();
        
        //Se guarda en 'path' la ubicacion del archivo elegido que sera la foto de perfil
        String path_img = this.im.getAbsolutePath();
        
        //Se toma la imagen y se define como un icono asignable
        ImageIcon img = new ImageIcon(new ImageIcon(path_img).getImage().getScaledInstance(100, 100, Image.SCALE_DEFAULT));
        this.BTN_Foto.setText("");
        this.BTN_Foto.setIcon(img);
    }//GEN-LAST:event_BTN_FotoActionPerformed

    private void BTN_CrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_CrearActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_BTN_CrearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VNT_Singup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VNT_Singup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VNT_Singup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VNT_Singup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VNT_Singup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_Crear;
    private javax.swing.JButton BTN_Foto;
    private javax.swing.JTextField FLD_Email;
    private javax.swing.JPasswordField FLD_Nombre;
    private javax.swing.JPasswordField FLD_Password1;
    private javax.swing.JPasswordField FLD_Password2;
    private javax.swing.JTextField FLD_Tel;
    private javax.swing.JSpinner SPN_Anio;
    private javax.swing.JSpinner SPN_Dia;
    private javax.swing.JSpinner SPN_Mes;
    private javax.swing.JLabel TXT_Email;
    private javax.swing.JLabel TXT_FechaN;
    private javax.swing.JLabel TXT_Nombre;
    private javax.swing.JLabel TXT_Password1;
    private javax.swing.JLabel TXT_Password2;
    private javax.swing.JLabel TXT_Tel;
    // End of variables declaration//GEN-END:variables
}
