
package com.mycompany.mavenproject1;

import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author Vicente193373
 */
public class VNT_Login extends javax.swing.JFrame {
    
    public VNT_Login() 
    {
        initComponents();
        
        String url = "src/main/java/images/Direction.png";
        ImageIcon image = new ImageIcon(url);
        Image img = image.getImage().getScaledInstance(100, 100, Image.SCALE_DEFAULT);
        ImageIcon icono = new ImageIcon(img);
        LBL_Logo.setIcon(icono);
        
        System.out.println("   JFRAME 'VNT_Login' HAS BEEN INICIATED\n");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FLD_Pass = new javax.swing.JPasswordField();
        FLD_Identif = new javax.swing.JTextField();
        BTN_Crear = new javax.swing.JButton();
        LBL_TextD = new javax.swing.JLabel();
        TXT_Identif = new javax.swing.JLabel();
        TXT_Password = new javax.swing.JLabel();
        BTN_Entrar = new javax.swing.JButton();
        LBL_Logo = new javax.swing.JLabel();
        LBL_Warning = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1015, 615));

        BTN_Crear.setText("Crear una Cuenta");
        BTN_Crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_CrearActionPerformed(evt);
            }
        });

        LBL_TextD.setText("  ó  ");

        TXT_Identif.setText("Correo Electronico");

        TXT_Password.setText("Contraseña");

        BTN_Entrar.setText("Entrar");
        BTN_Entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_EntrarActionPerformed(evt);
            }
        });

        LBL_Logo.setBackground(new java.awt.Color(204, 204, 204));

        LBL_Warning.setForeground(new java.awt.Color(255, 0, 51));
        LBL_Warning.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBL_Warning.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(470, 470, 470)
                .addComponent(LBL_Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(251, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BTN_Entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LBL_TextD)
                                .addGap(86, 86, 86))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TXT_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(FLD_Pass)
                                    .addComponent(BTN_Crear, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TXT_Identif, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FLD_Identif, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(424, 424, 424))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(LBL_Warning, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(243, 243, 243))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(LBL_Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(TXT_Identif)
                .addGap(1, 1, 1)
                .addComponent(FLD_Identif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(TXT_Password)
                .addGap(1, 1, 1)
                .addComponent(FLD_Pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LBL_Warning, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(BTN_Entrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LBL_TextD)
                .addGap(16, 16, 16)
                .addComponent(BTN_Crear)
                .addGap(155, 155, 155))
        );

        FLD_Pass.getAccessibleContext().setAccessibleName("ID_FLD_Password");
        FLD_Identif.getAccessibleContext().setAccessibleName("ID_FLD_Identif");
        FLD_Identif.getAccessibleContext().setAccessibleDescription("");
        BTN_Crear.getAccessibleContext().setAccessibleName("ID_BTN_Crear");
        TXT_Identif.getAccessibleContext().setAccessibleName("ID_TXT_Identif");
        TXT_Identif.getAccessibleContext().setAccessibleDescription("");
        TXT_Password.getAccessibleContext().setAccessibleName("ID_TXT_Password");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_CrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_CrearActionPerformed
        // TODO add your handling code here:
        
        //Se crea una ventana para crear una cuenta nueva
        VNT_Singup sing = new VNT_Singup();
        
        //Se hace visible a la ventana de singup
        sing.setVisible(true);
        
        //Se hace invisible y se desaparece la ventana de login actual
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_BTN_CrearActionPerformed

    //Funcion que se activa al presionar el boton de ingreso
    private void BTN_EntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_EntrarActionPerformed
        
        try 
        {
            //Se define la conexion usando el archivo predefinido DB_con.java
            DB_con db_c = new DB_con();
            
            //Se define la conexion en a para referenciarla
            Connection a = db_c.Get_conexion();
            
            //Se guarda en 'usr' lo que estaba escrito en el campo de identificacion
            String usr = FLD_Identif.getText();
            
            //Se guarda en 'psw' lo que estaba escrito en el campo de contraseña
            String psw  = FLD_Pass.getText();
            
            //Se obtiene el registro del usuario buscado
            ResultSet login = db_c.Ex_select(usr, psw);
            
            if (login == null) //Comprueba que login tuvo un resultado valido
            {
                if(a == null)
                {
                    LBL_Warning.setText("Comprueba tu contraseña MySQL o Nombre de la Base en DB_con.java");
                }
                else
                {
                    LBL_Warning.setText("Fallo inicio de sesion");
                }
                System.out.println("\n   Error VNT_Login: login es null \n\n");
            }
            else//if(login.next() == true) //se comprueba que los datos para entrar si existen y son correctos
            {
                //Como hubo exito en encontrar un registro se guarda el id del usuario
                String User_ID = login.getString("id_usuario");
                
                System.out.println("\n   Iniciando sesion " + User_ID + "... \n\n");
                
                //Se crea una ventana de inicio
                VNT_Inicio NewVI = new VNT_Inicio();
                
                //Se pasa el ID_del usuario que inicio sesion
                NewVI.recieveID(User_ID);
                
                //Se hace visible a la ventana de inicio
                NewVI.setVisible(true);
                
                //Se hace invisible y se desaparece la ventana de login actual
                this.setVisible(false);
                this.dispose();
            }
            
        } 
        catch (SQLException ex) 
        {
            Logger.getLogger(VNT_Login.class.getName()).log(Level.SEVERE, null, ex);
            //System.out.println("\n   Error VNT_Login: SQLException \n\n");
            this.setVisible(false);
            this.dispose();
        }
        
    }//GEN-LAST:event_BTN_EntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VNT_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VNT_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VNT_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VNT_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VNT_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_Crear;
    private javax.swing.JButton BTN_Entrar;
    private javax.swing.JTextField FLD_Identif;
    private javax.swing.JPasswordField FLD_Pass;
    private javax.swing.JLabel LBL_Logo;
    private javax.swing.JLabel LBL_TextD;
    private javax.swing.JLabel LBL_Warning;
    private javax.swing.JLabel TXT_Identif;
    private javax.swing.JLabel TXT_Password;
    // End of variables declaration//GEN-END:variables
}
