/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1;

import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.awt.Font;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Vicente193373
 */
public class VNT_Configuracion extends javax.swing.JFrame {

    /**
     * Creates new form VNT_Inicio
     */
    String Main_ID;
    
    public VNT_Configuracion() {
        initComponents();
        
    }
    
    public void recieveID(String variable) {
        this.Main_ID = variable;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        BTN_Inicio = new javax.swing.JButton();
        BTN_Explorar = new javax.swing.JButton();
        BTN_Notif = new javax.swing.JButton();
        BTN_Perfil = new javax.swing.JButton();
        BTN_Config = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 50), new java.awt.Dimension(0, 50), new java.awt.Dimension(32767, 50));
        BTN_Color = new javax.swing.JButton();
        BTN_Fuente = new javax.swing.JButton();
        BTN_Notificaciones = new javax.swing.JButton();
        BTN_Idioma = new javax.swing.JButton();
        LBL_Titulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        BTN_Inicio.setBackground(new java.awt.Color(30, 30, 30));
        BTN_Inicio.setFont(new java.awt.Font("Monospaced", 2, 24)); // NOI18N
        BTN_Inicio.setForeground(new java.awt.Color(255, 255, 255));
        BTN_Inicio.setText("Inicio");
        BTN_Inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_InicioActionPerformed(evt);
            }
        });

        BTN_Explorar.setBackground(new java.awt.Color(30, 30, 30));
        BTN_Explorar.setFont(new java.awt.Font("Monospaced", 2, 24)); // NOI18N
        BTN_Explorar.setForeground(new java.awt.Color(255, 255, 255));
        BTN_Explorar.setText("Explorar");
        BTN_Explorar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ExplorarActionPerformed(evt);
            }
        });

        BTN_Notif.setBackground(new java.awt.Color(30, 30, 30));
        BTN_Notif.setFont(new java.awt.Font("Monospaced", 2, 24)); // NOI18N
        BTN_Notif.setForeground(new java.awt.Color(255, 255, 255));
        BTN_Notif.setText("Notificaciones");
        BTN_Notif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_NotifActionPerformed(evt);
            }
        });

        BTN_Perfil.setBackground(new java.awt.Color(30, 30, 30));
        BTN_Perfil.setFont(new java.awt.Font("Monospaced", 2, 24)); // NOI18N
        BTN_Perfil.setForeground(new java.awt.Color(255, 255, 255));
        BTN_Perfil.setText("Perfil");
        BTN_Perfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_PerfilActionPerformed(evt);
            }
        });

        BTN_Config.setBackground(new java.awt.Color(30, 30, 30));
        BTN_Config.setFont(new java.awt.Font("Monospaced", 3, 24)); // NOI18N
        BTN_Config.setForeground(new java.awt.Color(255, 255, 255));
        BTN_Config.setText("Configuración");
        BTN_Config.setToolTipText("");
        BTN_Config.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ConfigActionPerformed(evt);
            }
        });

        BTN_Color.setText("Color de fondo");
        BTN_Color.setActionCommand("");
        BTN_Color.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BTN_Color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ColorActionPerformed(evt);
            }
        });

        BTN_Fuente.setText("Tamaño de Fuente");
        BTN_Fuente.setActionCommand("");
        BTN_Fuente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BTN_Fuente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_FuenteActionPerformed(evt);
            }
        });

        BTN_Notificaciones.setText("Notificaciones");
        BTN_Notificaciones.setActionCommand("");
        BTN_Notificaciones.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BTN_Notificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_NotificacionesActionPerformed(evt);
            }
        });

        BTN_Idioma.setText("Idiomas");
        BTN_Idioma.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BTN_Idioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_IdiomaActionPerformed(evt);
            }
        });

        LBL_Titulo.setFont(new java.awt.Font("Monospaced", 2, 24)); // NOI18N
        LBL_Titulo.setText("Configuración");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BTN_Notif)
                    .addComponent(BTN_Perfil, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTN_Config, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTN_Inicio, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTN_Explorar, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(12, 12, 12)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(BTN_Color, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTN_Fuente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTN_Notificaciones, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTN_Idioma, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LBL_Titulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 246, Short.MAX_VALUE)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(168, 168, 168)
                                .addComponent(BTN_Inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BTN_Explorar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BTN_Notif, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BTN_Perfil, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BTN_Config, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LBL_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(BTN_Color, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BTN_Fuente, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BTN_Notificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BTN_Idioma, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(223, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        BTN_Inicio.getAccessibleContext().setAccessibleName("ID_BTN_Inicio");
        BTN_Explorar.getAccessibleContext().setAccessibleName("ID_BTN_Buscar");
        BTN_Notif.getAccessibleContext().setAccessibleName("ID_BTN_Notif");
        BTN_Perfil.getAccessibleContext().setAccessibleName("ID_BTN_Perfil");
        BTN_Config.getAccessibleContext().setAccessibleName("ID_BTN_Config");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private ResourceBundle localBundle;
    
    private void BTN_InicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_InicioActionPerformed
        // TODO add your handling code here:
        VNT_Inicio NewVI = new VNT_Inicio();
        
        System.out.println("\n   Comprobando Sesion " + Main_ID + "... \n\n");
        
        //Se pasa el ID_del usuario que inicio sesion
        NewVI.recieveID(Main_ID);
        
        //Se hace visible a la ventana de inicio
        NewVI.setVisible(true);
        
        //Se hace invisible y se desaparece la ventana de login actual
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_BTN_InicioActionPerformed

    private void BTN_ExplorarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ExplorarActionPerformed
        // TODO add your handling code here:
        VNT_Explorar NewVE = new VNT_Explorar();
        NewVE.recieveID(Main_ID);
        NewVE.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_BTN_ExplorarActionPerformed

    private void BTN_NotifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_NotifActionPerformed
        // TODO add your handling code here:
        VNT_Notif NewVN = new VNT_Notif();
        NewVN.recieveID(Main_ID);
        NewVN.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_BTN_NotifActionPerformed

    private void BTN_PerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_PerfilActionPerformed
        // TODO add your handling code here:
        VNT_Perfil NewVP = new VNT_Perfil();
        System.out.println("\n   " + Main_ID + " Transportado \n\n");
        NewVP.recieveIDs(Main_ID, Main_ID);
        NewVP.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_BTN_PerfilActionPerformed

    private void BTN_ConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ConfigActionPerformed
        // TODO add your handling code here:
        VNT_Configuracion NewVCn = new VNT_Configuracion();
        NewVCn.recieveID(Main_ID);
        NewVCn.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_BTN_ConfigActionPerformed

    private void BTN_ColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ColorActionPerformed
        // TODO add your handling code here:
        String[] opciones = {"Azul", "Verde", "Claro", "Oscuro"};
        int seleccion = JOptionPane.showOptionDialog(
            this,
            "Selecciona un color de fondo:",
            "Cambiar color",
            JOptionPane.DEFAULT_OPTION,
            JOptionPane.PLAIN_MESSAGE,
            null,
            opciones,
            opciones[0]
        );

        Color nuevoColor = getBackground();  // Color actual por defecto

        switch (seleccion) {
            case 0:
                nuevoColor = new Color(173, 216, 230); // Azul claro
                break;
            case 1:
                nuevoColor = new Color(144, 238, 144); // Verde claro
                break;
            case 2:
                nuevoColor = new Color(211, 211, 211); // Gris claro
                break;
            case 3:
                nuevoColor = new Color(30, 30, 30); // Gris Oscuro
                break;
            default:
                return; // Si cierra el diálogo, no hace nada
        }

        // Aplica el color al panel principal
        getContentPane().setBackground(nuevoColor);

        // También puedes aplicar a otros paneles si los tienes
        // panelFondo.setBackground(nuevoColor); 
    }//GEN-LAST:event_BTN_ColorActionPerformed

    private void BTN_FuenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_FuenteActionPerformed
        // TODO add your handling code here:
        String[] opciones = {"Pequeño", "Mediano", "Grande"};

        int seleccion = JOptionPane.showOptionDialog(
            this,
            "Selecciona el tamaño de fuente:",
            "Configuración de fuente",
            JOptionPane.DEFAULT_OPTION,
            JOptionPane.PLAIN_MESSAGE,
            null,
            opciones,
            opciones[1]
        );

        int nuevoTamano;
        switch (seleccion) {
            case 0:
                nuevoTamano = 12;
                break;
            case 1:
                nuevoTamano = 16;
                break;
            case 2:
                nuevoTamano = 20;
                break;
            default:
                return; // Usuario canceló o cerró el diálogo
        }

        // Aplicamos el cambio de fuente a toda la ventana
        cambiarFuente(this.getContentPane(), nuevoTamano);
        LBL_Titulo.setFont(LBL_Titulo.getFont().deriveFont((float) nuevoTamano));
        
        this.pack(); // ajusta tamaño de ventana a sus componentes
        this.revalidate(); // refresca el layout
        this.repaint();    // repinta la ventana

    }//GEN-LAST:event_BTN_FuenteActionPerformed

    private void BTN_NotificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_NotificacionesActionPerformed
        // TODO add your handling code here:
            Object[] opciones = {"Activar notificaciones", "Desactivar notificaciones"};
       int seleccion = javax.swing.JOptionPane.showOptionDialog(
           this,
           "Seleccione una opción:",
           "Configuración de notificaciones",
           javax.swing.JOptionPane.DEFAULT_OPTION,
           javax.swing.JOptionPane.QUESTION_MESSAGE,
           null,
           opciones,
           opciones[0]
       );

       if (seleccion == 0) {
           ConfigGlobal.notificacionesActivadas = true;
           javax.swing.JOptionPane.showMessageDialog(this, "Notificaciones activadas.");
       } else if (seleccion == 1) {
           ConfigGlobal.notificacionesActivadas = false;
           javax.swing.JOptionPane.showMessageDialog(this, "Notificaciones desactivadas.");
       }
    }//GEN-LAST:event_BTN_NotificacionesActionPerformed

    private void BTN_IdiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_IdiomaActionPerformed
        // TODO add your handling code here:
        String[] opciones = {"Español", "Inglés"};
        int seleccion = JOptionPane.showOptionDialog(
            this,
            IdiomaManager.getTexto("label.seleccionar_idioma"),
            IdiomaManager.getTexto("btn.idioma"),
            JOptionPane.DEFAULT_OPTION,
            JOptionPane.INFORMATION_MESSAGE,
            null,
            opciones,
            opciones[0]
        );

        if (seleccion == 0) {
            localBundle = ResourceBundle.getBundle("com.mycompany.mavenproject1.messages", new Locale("es"));
        } else if (seleccion == 1) {
            localBundle = ResourceBundle.getBundle("com.mycompany.mavenproject1.messages", new Locale("en"));
        }

        actualizarTextos();
    }//GEN-LAST:event_BTN_IdiomaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VNT_Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VNT_Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VNT_Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VNT_Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VNT_Configuracion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_Color;
    private javax.swing.JButton BTN_Config;
    private javax.swing.JButton BTN_Explorar;
    private javax.swing.JButton BTN_Fuente;
    private javax.swing.JButton BTN_Idioma;
    private javax.swing.JButton BTN_Inicio;
    private javax.swing.JButton BTN_Notif;
    private javax.swing.JButton BTN_Notificaciones;
    private javax.swing.JButton BTN_Perfil;
    private javax.swing.JLabel LBL_Titulo;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables

    private void actualizarTextos() {
        BTN_Inicio.setText(localBundle.getString("btn.inicio"));
        BTN_Explorar.setText(localBundle.getString("btn.explorar"));
        BTN_Notif.setText(localBundle.getString("btn.notificaciones"));
        BTN_Perfil.setText(localBundle.getString("btn.perfil"));
        BTN_Config.setText(localBundle.getString("btn.configuracion"));

        LBL_Titulo.setText(localBundle.getString("label.configuracion"));

        BTN_Color.setText(localBundle.getString("btn.premium"));
        BTN_Fuente.setText(localBundle.getString("btn.suscripciones"));
        BTN_Notificaciones.setText(localBundle.getString("btn.notificaciones.config"));
        BTN_Idioma.setText(localBundle.getString("btn.idioma"));

    }

    private void cambiarFuente(Component componente, int nuevoTamano) {
        if (componente instanceof JLabel || 
            componente instanceof JButton || 
            componente instanceof JTextArea || 
            componente instanceof JTextField || 
            componente instanceof JCheckBox || 
            componente instanceof JRadioButton || 
            componente instanceof JTable || 
            componente instanceof JComboBox) {

            Font fuenteActual = componente.getFont();
            componente.setFont(fuenteActual.deriveFont((float) nuevoTamano));
        }

        // Si el componente es un contenedor, aplicamos recursivamente a sus hijos
        if (componente instanceof Container) {
            for (Component hijo : ((Container) componente).getComponents()) {
                cambiarFuente(hijo, nuevoTamano);
            }
        }
    }


}
