/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;


/**
 *
 * @author Vicente193373
 */
public class VNT_Inicio extends javax.swing.JFrame {

    /**
     * Creates new form VNT_Inicio
     */
    int Pub_index = -1;
    int Shw_index = -1;
    int Shw_index1 = 0;
    
    String Main_ID;
    String Show_ID;
    
    ImageIcon[] Pub_Photo;
    String[] Pub_Name;
    String[] Pub_Id;    
    String[] Pub_Date;
    String[] Pub_Content;
    int[] Pub_Likes;
    
    public VNT_Inicio() 
    {
        initComponents();
        Set_Show();
        Pub_Show();
        System.out.println("   JFRAME 'VNT_Inicio' HAS BEEN INICIATED\n");
    }
        
    /**z
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void recieveID(String variable) {
        this.Main_ID = variable;
        System.out.println("\n   Sesion " + Main_ID + " Iniciada \n\n");
    }
    
    public void ReloadVI()
    {
        VNT_Inicio NewVI = new VNT_Inicio();
        
        //Se pasa el ID_del usuario que inicio sesion
        NewVI.recieveID(Main_ID);

        //Se hace visible a la ventana de inicio
        NewVI.setVisible(true);
        
        //Se hace invisible y se desaparece la ventana de login actual
        this.setVisible(false);
        this.dispose();
    }
    
    private void Set_Show()
    {
        try 
        {
            DB_con db_c = new DB_con();
            ResultSet tweet = db_c.Tbl_Extract("Tweet");
            
            //Al abrir se registran las publicaciones presentes en la base de datos
            while(tweet.next())
            {
                Pub_index = Pub_index + 1;
                
                Pub_Id[Pub_index] = tweet.getString("id_usuario");
                Pub_Date[Pub_index] = tweet.getString("fecha_publicacion");
                Pub_Content[Pub_index] = tweet.getString("contenido");
                Pub_Photo[Pub_index] = db_c.Prfl_Photo(Pub_Id[Pub_index], BTN_PubPhoto.getHeight(), BTN_PubPhoto.getWidth());
                Pub_Name[Pub_index] = db_c.Adyacent_Element( "nombre", "Usuario", Pub_Id[Pub_index], "id_usuario");
                Pub_Likes[Pub_index] = db_c.Numero_en_tweet(tweet.getString("id_tweet"), "MeGusta");
            }
        } 
        catch (SQLException ex) 
        {
            Logger.getLogger(VNT_Inicio.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("\n   Error VNT_Inicio: SQLException \n\n");
        }
        
        if(Pub_index == 0)
        {
            Shw_index = 0;
        }
        
        if(Pub_index > 0)
        {
            Shw_index = 0;
            Shw_index1 = 1;
        }
    }
    
    private void Pub_Show()
    {
        //Se muestran las publicaciones presentes en la base de datos en la pagina inicial
        if (Shw_index >= 0 && Shw_index <= Pub_index)
        {
            
            LBL_Id.setVisible(true);
            LBL_Date.setVisible(true);
            TXT_Content.setVisible(true);
            BTN_PubPhoto.setVisible(true);
            LBL_Name.setVisible(true);
            BTN_Respuesta.setVisible(true);
            BTN_Repost.setVisible(true);
            BTN_MeGusta.setVisible(true);
            SCR_Pub.setVisible(true);
            
            LBL_Id.setText(Pub_Id[Shw_index]);
            LBL_Date.setText(Pub_Date[Shw_index]);
            TXT_Content.setText(Pub_Content[Shw_index]);
            BTN_PubPhoto.setIcon(Pub_Photo[Shw_index]);
            LBL_Name.setText(Pub_Name[Shw_index]);
            BTN_MeGusta.setText(String.valueOf(Pub_Likes[Shw_index]));
        }
        else
        {
            LBL_Id.setVisible(false);
            LBL_Date.setVisible(false);
            TXT_Content.setVisible(false);
            BTN_PubPhoto.setVisible(false);
            LBL_Name.setVisible(false);
            BTN_Respuesta.setVisible(false);
            BTN_Repost.setVisible(false);
            BTN_MeGusta.setVisible(false);
            SCR_Pub.setVisible(false);
        }
        
        if (Shw_index1 >= 1 && Shw_index1 <= Pub_index)
        {
            LBL_Id1.setVisible(true);
            LBL_Date1.setVisible(true);
            TXT_Content1.setVisible(true);
            BTN_PubPhoto1.setVisible(true);
            LBL_Name1.setVisible(true);
            BTN_Respuesta1.setVisible(true);
            BTN_Repost1.setVisible(true);
            BTN_MeGusta1.setVisible(true);
            SCR_Pub1.setVisible(true);
            
            LBL_Id1.setText(Pub_Id[Shw_index1]);
            LBL_Date1.setText(Pub_Date[Shw_index1]);
            TXT_Content1.setText(Pub_Content[Shw_index1]);
            BTN_PubPhoto1.setIcon(Pub_Photo[Shw_index1]);
            LBL_Name1.setText(Pub_Name[Shw_index1]);
            BTN_MeGusta1.setText(String.valueOf(Pub_Likes[Shw_index1]));
        }
        else
        {
            LBL_Id1.setVisible(false);
            LBL_Date1.setVisible(false);
            TXT_Content1.setVisible(false);
            BTN_PubPhoto1.setVisible(false);
            LBL_Name1.setVisible(false);
            BTN_Respuesta1.setVisible(false);
            BTN_Repost1.setVisible(false);
            BTN_MeGusta1.setVisible(false);
            SCR_Pub1.setVisible(false);
        }
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        BTN_Inicio = new javax.swing.JButton();
        BTN_Explorar = new javax.swing.JButton();
        BTN_Notif = new javax.swing.JButton();
        BTN_Perfil = new javax.swing.JButton();
        BTN_Config = new javax.swing.JButton();
        FLD_Buscar = new javax.swing.JTextField();
        BTN_Buscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        FLD_Publicar = new javax.swing.JTextArea();
        BTN_Publicar = new javax.swing.JButton();
        BTN_Comun = new javax.swing.JButton();
        BTN_Listas = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 50), new java.awt.Dimension(0, 50), new java.awt.Dimension(32767, 50));
        LST_Tendencias = new java.awt.List();
        PAN_Posts = new java.awt.ScrollPane();
        PNL_Pub = new javax.swing.JPanel();
        BTN_PubPhoto = new javax.swing.JButton();
        LBL_Name = new javax.swing.JLabel();
        LBL_Id = new javax.swing.JLabel();
        LBL_Date = new javax.swing.JLabel();
        BTN_Respuesta = new javax.swing.JButton();
        BTN_Repost = new javax.swing.JButton();
        BTN_MeGusta = new javax.swing.JButton();
        BTN_Ant = new javax.swing.JButton();
        BTN_Sig = new javax.swing.JButton();
        SCR_Pub = new javax.swing.JScrollPane();
        TXT_Content = new javax.swing.JTextPane();
        BTN_PubPhoto1 = new javax.swing.JButton();
        LBL_Name1 = new javax.swing.JLabel();
        SCR_Pub1 = new javax.swing.JScrollPane();
        TXT_Content1 = new javax.swing.JTextPane();
        LBL_Id1 = new javax.swing.JLabel();
        LBL_Date1 = new javax.swing.JLabel();
        BTN_Respuesta1 = new javax.swing.JButton();
        BTN_Repost1 = new javax.swing.JButton();
        BTN_MeGusta1 = new javax.swing.JButton();
        LBL_Warning = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setForeground(java.awt.Color.darkGray);
        setSize(new java.awt.Dimension(1015, 615));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        BTN_Inicio.setBackground(new java.awt.Color(30, 30, 30));
        BTN_Inicio.setFont(new java.awt.Font("Monospaced", 3, 24)); // NOI18N
        BTN_Inicio.setForeground(new java.awt.Color(255, 255, 255));
        BTN_Inicio.setText("Inicio");
        BTN_Inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_InicioActionPerformed(evt);
            }
        });

        BTN_Explorar.setBackground(new java.awt.Color(30, 30, 30));
        BTN_Explorar.setFont(new java.awt.Font("Monospaced", 2, 24)); // NOI18N
        BTN_Explorar.setForeground(new java.awt.Color(255, 255, 255));
        BTN_Explorar.setText("Explorar");
        BTN_Explorar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ExplorarActionPerformed(evt);
            }
        });

        BTN_Notif.setBackground(new java.awt.Color(30, 30, 30));
        BTN_Notif.setFont(new java.awt.Font("Monospaced", 2, 24)); // NOI18N
        BTN_Notif.setForeground(new java.awt.Color(255, 255, 255));
        BTN_Notif.setText("Notificaciones");
        BTN_Notif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_NotifActionPerformed(evt);
            }
        });

        BTN_Perfil.setBackground(new java.awt.Color(30, 30, 30));
        BTN_Perfil.setFont(new java.awt.Font("Monospaced", 2, 24)); // NOI18N
        BTN_Perfil.setForeground(new java.awt.Color(255, 255, 255));
        BTN_Perfil.setText("Perfil");
        BTN_Perfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_PerfilActionPerformed(evt);
            }
        });

        BTN_Config.setBackground(new java.awt.Color(30, 30, 30));
        BTN_Config.setFont(new java.awt.Font("Monospaced", 2, 24)); // NOI18N
        BTN_Config.setForeground(new java.awt.Color(255, 255, 255));
        BTN_Config.setText("Configuración");
        BTN_Config.setToolTipText("");
        BTN_Config.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ConfigActionPerformed(evt);
            }
        });

        BTN_Buscar.setText("Buscar");

        FLD_Publicar.setColumns(20);
        FLD_Publicar.setRows(5);
        FLD_Publicar.setText("Que estas pensando?");
        FLD_Publicar.setToolTipText("");
        jScrollPane1.setViewportView(FLD_Publicar);
        FLD_Publicar.getAccessibleContext().setAccessibleName("ID_FLD_Publicar");

        BTN_Publicar.setText("Postear");
        BTN_Publicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_PublicarActionPerformed(evt);
            }
        });

        BTN_Comun.setBackground(new java.awt.Color(30, 30, 30));
        BTN_Comun.setFont(new java.awt.Font("Monospaced", 2, 24)); // NOI18N
        BTN_Comun.setForeground(new java.awt.Color(255, 255, 255));
        BTN_Comun.setText("Comunidades");
        BTN_Comun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ComunActionPerformed(evt);
            }
        });

        BTN_Listas.setBackground(new java.awt.Color(30, 30, 30));
        BTN_Listas.setFont(new java.awt.Font("Monospaced", 2, 24)); // NOI18N
        BTN_Listas.setForeground(new java.awt.Color(255, 255, 255));
        BTN_Listas.setText("Listas");
        BTN_Listas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ListasActionPerformed(evt);
            }
        });

        LST_Tendencias.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        LST_Tendencias.setName("Tendencias"); // NOI18N

        PAN_Posts.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PAN_Posts.setForeground(new java.awt.Color(51, 51, 51));
        PAN_Posts.setName("Posts"); // NOI18N

        BTN_PubPhoto.setSelected(true);

        LBL_Name.setText("Name");

        LBL_Id.setForeground(new java.awt.Color(153, 153, 153));
        LBL_Id.setText("@Id");

        LBL_Date.setForeground(new java.awt.Color(153, 153, 153));
        LBL_Date.setText("23/03/25");

        BTN_Respuesta.setBackground(new java.awt.Color(153, 153, 153));
        BTN_Respuesta.setText("ANS");
        BTN_Respuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_RespuestaActionPerformed(evt);
            }
        });

        BTN_Repost.setBackground(new java.awt.Color(153, 153, 153));
        BTN_Repost.setText("REP");
        BTN_Repost.setToolTipText("");
        BTN_Repost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_RepostActionPerformed(evt);
            }
        });

        BTN_MeGusta.setBackground(new java.awt.Color(153, 153, 153));
        BTN_MeGusta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_MeGustaActionPerformed(evt);
            }
        });

        BTN_Ant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_AntActionPerformed(evt);
            }
        });

        BTN_Sig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_SigActionPerformed(evt);
            }
        });

        TXT_Content.setEditable(false);
        TXT_Content.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        TXT_Content.setText("the quick brown fox jump over the lazy dog in the afternoon of this soon to be lost place in the wilderness at the bottom of these food chains; one two three four five six seven eight nine ten eleven twelve apple chocolate beans pepper soda books water desks walls numbers toughts death space universe ants goku dddd dd d d   d d d d d d d dddd ddddd d d d dd dddd dd dddd dddd d ddd dddd d ddd ddd dddd dddddddd ddd dd dd ddddd dddd d d ");
        SCR_Pub.setViewportView(TXT_Content);

        BTN_PubPhoto1.setSelected(true);

        LBL_Name1.setText("Name");

        TXT_Content1.setEditable(false);
        TXT_Content1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        TXT_Content1.setText("the quick brown fox jump over the lazy dog in the afternoon of this soon to be lost place in the wilderness at the bottom of these food chains; one two three four five six seven eight nine ten eleven twelve apple chocolate beans pepper soda books water desks walls numbers toughts death space universe ants goku dddd dd d d   d d d d d d d dddd ddddd d d d dd dddd dd dddd dddd d ddd dddd d ddd ddd dddd dddddddd ddd dd dd ddddd dddd d d ");
        SCR_Pub1.setViewportView(TXT_Content1);

        LBL_Id1.setForeground(new java.awt.Color(153, 153, 153));
        LBL_Id1.setText("@Id");

        LBL_Date1.setForeground(new java.awt.Color(153, 153, 153));
        LBL_Date1.setText("23/03/25");

        BTN_Respuesta1.setBackground(new java.awt.Color(153, 153, 153));
        BTN_Respuesta1.setText("ANS");
        BTN_Respuesta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_Respuesta1ActionPerformed(evt);
            }
        });

        BTN_Repost1.setBackground(new java.awt.Color(153, 153, 153));
        BTN_Repost1.setText("REP");
        BTN_Repost1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_Repost1ActionPerformed(evt);
            }
        });

        BTN_MeGusta1.setBackground(new java.awt.Color(153, 153, 153));
        BTN_MeGusta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_MeGusta1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PNL_PubLayout = new javax.swing.GroupLayout(PNL_Pub);
        PNL_Pub.setLayout(PNL_PubLayout);
        PNL_PubLayout.setHorizontalGroup(
            PNL_PubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNL_PubLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(PNL_PubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PNL_PubLayout.createSequentialGroup()
                        .addComponent(BTN_PubPhoto1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(PNL_PubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PNL_PubLayout.createSequentialGroup()
                                .addComponent(LBL_Name1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LBL_Id1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LBL_Date1))
                            .addGroup(PNL_PubLayout.createSequentialGroup()
                                .addComponent(BTN_Respuesta1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(98, 98, 98)
                                .addComponent(BTN_Repost1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(98, 98, 98)
                                .addComponent(BTN_MeGusta1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PNL_PubLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(SCR_Pub1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(PNL_PubLayout.createSequentialGroup()
                        .addComponent(BTN_PubPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(PNL_PubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PNL_PubLayout.createSequentialGroup()
                                .addComponent(LBL_Name)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LBL_Id)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LBL_Date))
                            .addGroup(PNL_PubLayout.createSequentialGroup()
                                .addComponent(BTN_Respuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(98, 98, 98)
                                .addComponent(BTN_Repost, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(98, 98, 98)
                                .addComponent(BTN_MeGusta, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PNL_PubLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(SCR_Pub, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(30, 49, Short.MAX_VALUE))
            .addGroup(PNL_PubLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BTN_Sig, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(PNL_PubLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BTN_Ant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );
        PNL_PubLayout.setVerticalGroup(
            PNL_PubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNL_PubLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BTN_Ant, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PNL_PubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTN_PubPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PNL_PubLayout.createSequentialGroup()
                        .addGroup(PNL_PubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LBL_Name)
                            .addComponent(LBL_Id)
                            .addComponent(LBL_Date))
                        .addGap(1, 1, 1)
                        .addComponent(SCR_Pub, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PNL_PubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTN_Repost, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_MeGusta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_Respuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(PNL_PubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTN_PubPhoto1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PNL_PubLayout.createSequentialGroup()
                        .addGroup(PNL_PubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LBL_Name1)
                            .addComponent(LBL_Id1)
                            .addComponent(LBL_Date1))
                        .addGap(1, 1, 1)
                        .addComponent(SCR_Pub1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PNL_PubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTN_Repost1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_MeGusta1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_Respuesta1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(BTN_Sig, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PAN_Posts.add(PNL_Pub);

        LBL_Warning.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(BTN_Notif)
                        .addComponent(BTN_Perfil, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(BTN_Config, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(BTN_Inicio, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(BTN_Explorar, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(BTN_Listas)
                    .addComponent(BTN_Comun))
                .addGap(12, 12, 12)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
                    .addComponent(PAN_Posts, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(LBL_Warning, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTN_Publicar)
                        .addGap(9, 9, 9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BTN_Buscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FLD_Buscar))
                    .addComponent(LST_Tendencias, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN_Buscar)
                    .addComponent(FLD_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(LST_Tendencias, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BTN_Publicar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LBL_Warning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PAN_Posts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(BTN_Inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BTN_Explorar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BTN_Notif, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BTN_Comun, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BTN_Listas, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BTN_Perfil, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BTN_Config, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85))
                    .addComponent(jSeparator1)))
        );

        BTN_Inicio.getAccessibleContext().setAccessibleName("ID_BTN_Inicio");
        BTN_Explorar.getAccessibleContext().setAccessibleName("ID_BTN_Buscar");
        BTN_Notif.getAccessibleContext().setAccessibleName("ID_BTN_Notif");
        BTN_Perfil.getAccessibleContext().setAccessibleName("ID_BTN_Perfil");
        BTN_Config.getAccessibleContext().setAccessibleName("ID_BTN_Config");
        FLD_Buscar.getAccessibleContext().setAccessibleName("ID_FLD_Publicar");
        BTN_Buscar.getAccessibleContext().setAccessibleName("ID_BTN_Buscar");
        BTN_Publicar.getAccessibleContext().setAccessibleName("ID_BTN_Publicar");
        BTN_Comun.getAccessibleContext().setAccessibleName("ID_BTN_Comun");
        BTN_Listas.getAccessibleContext().setAccessibleName("ID_BTN_Listas");
        LST_Tendencias.getAccessibleContext().setAccessibleName("ID_LST_Tendencias");
        PAN_Posts.getAccessibleContext().setAccessibleName("ID_PAN_Posts");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_InicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_InicioActionPerformed
        // TODO add your handling code here:
        this.ReloadVI();
    }//GEN-LAST:event_BTN_InicioActionPerformed

    private void BTN_ExplorarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ExplorarActionPerformed
        // Este bloque de codigo cierra esta ventana y abre la ventana de este boton
        VNT_Explorar NewVE = new VNT_Explorar();
        NewVE.recieveID(Main_ID);
        NewVE.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_BTN_ExplorarActionPerformed

    private void BTN_NotifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_NotifActionPerformed
        // Este bloque de codigo cierra esta ventana y abre la ventana de este boton
        VNT_Notif NewVN = new VNT_Notif();
        NewVN.recieveID(Main_ID);
        NewVN.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_BTN_NotifActionPerformed

    private void BTN_PerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_PerfilActionPerformed
        // Este bloque de codigo cierra esta ventana y abre la ventana de este boton
        VNT_Perfil NewVP = new VNT_Perfil();
        System.out.println("\n   " + Main_ID + " Transportado \n\n");
        NewVP.recieveIDs(Main_ID, Main_ID);
        NewVP.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_BTN_PerfilActionPerformed

    private void BTN_ConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ConfigActionPerformed
        // Este bloque de codigo cierra esta ventana y abre la ventana de este boton
        VNT_Configuracion NewVCn = new VNT_Configuracion();
        NewVCn.recieveID(Main_ID);
        NewVCn.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_BTN_ConfigActionPerformed

    private void BTN_ComunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ComunActionPerformed
        // Este bloque de codigo cierra esta ventana y abre la ventana de este boton
        VNT_Comunidades NewVCm = new VNT_Comunidades();
        NewVCm.recieveID(Main_ID);
        NewVCm.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_BTN_ComunActionPerformed

    private void BTN_ListasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ListasActionPerformed
        // Este bloque de codigo cierra esta ventana y abre la ventana de este boton
        VNT_Listas NewVL = new VNT_Listas();
        NewVL.recieveID(Main_ID);
        NewVL.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_BTN_ListasActionPerformed

    private void BTN_MeGustaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_MeGustaActionPerformed
        // TODO add your handling code here:
        DB_con db_c = new DB_con();
        String tweetid = db_c.Adyacent_Element( "id_tweet", "Tweet", TXT_Content.getText(), "contenido");
        Boolean Dar_like = db_c.NewLike(Main_ID, tweetid);
        
        if(Dar_like) //se comprueba que se publico el tweet correctamente
        {
            Pub_Likes[Shw_index]++;
            BTN_MeGusta.setText(String.valueOf(Pub_Likes[Shw_index]));
        }
        else
        {
            LBL_Warning.setText("Ocurrio un error");
            System.out.println("\n   Error VNT_Inicio: Fallo MeGusta0\n\n");
        }
    }//GEN-LAST:event_BTN_MeGustaActionPerformed

    private void BTN_RepostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_RepostActionPerformed
        // TODO add your handling code here:
        DB_con db_c = new DB_con();
        String post = LBL_Name.getText() + " " + LBL_Id.getText() + " " + LBL_Date.getText() + System.lineSeparator() + TXT_Content.getText();
        String tweetid = db_c.Adyacent_Element( "id_tweet", "Tweet", TXT_Content.getText(), "contenido");
        Boolean posted = db_c.Repostear(Main_ID, "Retweet", tweetid, post);
        
        if(posted) //se comprueba que se publico el tweet correctamente
        {
            this.ReloadVI();
        }
        else
        {
            LBL_Warning.setText("Ocurrio un error");
            System.out.println("\n   Error VNT_Inicio: Fallo Repost0\n\n");
        }
    }//GEN-LAST:event_BTN_RepostActionPerformed

    private void BTN_Repost1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_Repost1ActionPerformed
        // TODO add your handling code here:
        DB_con db_c = new DB_con();
        String post = LBL_Name1.getText() + LBL_Id1.getText() + LBL_Date1.getText() + System.lineSeparator() + TXT_Content1.getText();
        String tweetid = db_c.Adyacent_Element( "id_tweet", "Tweet", TXT_Content1.getText(), "contenido");
        Boolean posted = db_c.Repostear(Main_ID, "Retweet", tweetid, post);
        
        if(posted) //se comprueba que se publico el tweet correctamente
        {
            this.ReloadVI();
        }
        else
        {
            LBL_Warning.setText("Ocurrio un error");
            System.out.println("\n   Error VNT_Inicio: Fallo Repost1\n\n");
        }
    }//GEN-LAST:event_BTN_Repost1ActionPerformed

    private void BTN_MeGusta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_MeGusta1ActionPerformed
        // TODO add your handling code here:
        DB_con db_c = new DB_con();
        String tweetid = db_c.Adyacent_Element( "id_tweet", "Tweet", TXT_Content1.getText(), "contenido");
        Boolean Dar_like = db_c.NewLike(Main_ID, tweetid);
        
        if(Dar_like) //se comprueba que se publico el tweet correctamente
        {
            Pub_Likes[Shw_index1]++;
            BTN_MeGusta1.setText(String.valueOf(Pub_Likes[Shw_index1]));
        }
        else
        {
            LBL_Warning.setText("Ocurrio un error");
            System.out.println("\n   Error VNT_Inicio: Fallo MeGusta1 \n\n");
        }
    }//GEN-LAST:event_BTN_MeGusta1ActionPerformed

    private void BTN_AntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_AntActionPerformed
        //
        if(Shw_index > 0)
        {
            Shw_index = Shw_index - 2;
            Shw_index1 = Shw_index1 - 2;
            Pub_Show();
        }
    }//GEN-LAST:event_BTN_AntActionPerformed

    private void BTN_SigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_SigActionPerformed
        // TODO add your handling code here:
        if(Shw_index < Pub_index && Shw_index1 < Pub_index)
        {
            Shw_index = Shw_index + 2;
            Shw_index1 = Shw_index1 + 2;
            Pub_Show();
        }
    }//GEN-LAST:event_BTN_SigActionPerformed

    private void BTN_PublicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_PublicarActionPerformed
        // TODO add your handling code here:
        DB_con db_c = new DB_con();
        String post = FLD_Publicar.getText();
        boolean posted = db_c.Publicar(Main_ID, post);
        
        if(posted) //se comprueba que se publico el tweet correctamente
        {
            this.ReloadVI();
        }
        else
        {
            LBL_Warning.setText("Ocurrio un error");
            System.out.println("\n   Error VNT_Inicio: Fallo Publicacion\n\n");
        }
    }//GEN-LAST:event_BTN_PublicarActionPerformed

    private void BTN_RespuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_RespuestaActionPerformed
        // TODO add your handling code here:DB_con db_c = new DB_con();
        DB_con db_c = new DB_con();
        String post = " En respuesta a " + LBL_Id.getText() + ": " + System.lineSeparator() + FLD_Publicar.getText();
        String tweetid = db_c.Adyacent_Element( "id_tweet", "Tweet", TXT_Content.getText(), "contenido");
        Boolean posted = db_c.Repostear(Main_ID, "Comentario", tweetid, post);
        
        if(posted) //se comprueba que se publico el tweet correctamente
        {
            this.ReloadVI();
        }
        else
        {
            LBL_Warning.setText("Ocurrio un error");
            System.out.println("\n   Error VNT_Inicio: Fallo Respuesta0\n\n");
        }
    }//GEN-LAST:event_BTN_RespuestaActionPerformed

    private void BTN_Respuesta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_Respuesta1ActionPerformed
        // TODO add your handling code here:
        DB_con db_c = new DB_con();
        String post = " En respuesta a " + LBL_Id1.getText() + ": " + System.lineSeparator() + FLD_Publicar.getText();
        String tweetid = db_c.Adyacent_Element( "id_tweet", "Tweet", TXT_Content1.getText(), "contenido");
        Boolean posted = db_c.Repostear(Main_ID, "Comentario", tweetid, post);
        
        if(posted) //se comprueba que se publico el tweet correctamente
        {
            this.ReloadVI();
        }
        else
        {
            LBL_Warning.setText("Ocurrio un error");
            System.out.println("\n   Error VNT_Inicio: Fallo Respuesta1\n\n");
        }
    }//GEN-LAST:event_BTN_Respuesta1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VNT_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VNT_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VNT_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VNT_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VNT_Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_Ant;
    private javax.swing.JButton BTN_Buscar;
    private javax.swing.JButton BTN_Comun;
    private javax.swing.JButton BTN_Config;
    private javax.swing.JButton BTN_Explorar;
    private javax.swing.JButton BTN_Inicio;
    private javax.swing.JButton BTN_Listas;
    private javax.swing.JButton BTN_MeGusta;
    private javax.swing.JButton BTN_MeGusta1;
    private javax.swing.JButton BTN_Notif;
    private javax.swing.JButton BTN_Perfil;
    private javax.swing.JButton BTN_PubPhoto;
    private javax.swing.JButton BTN_PubPhoto1;
    private javax.swing.JButton BTN_Publicar;
    private javax.swing.JButton BTN_Repost;
    private javax.swing.JButton BTN_Repost1;
    private javax.swing.JButton BTN_Respuesta;
    private javax.swing.JButton BTN_Respuesta1;
    private javax.swing.JButton BTN_Sig;
    private javax.swing.JTextField FLD_Buscar;
    private javax.swing.JTextArea FLD_Publicar;
    private javax.swing.JLabel LBL_Date;
    private javax.swing.JLabel LBL_Date1;
    private javax.swing.JLabel LBL_Id;
    private javax.swing.JLabel LBL_Id1;
    private javax.swing.JLabel LBL_Name;
    private javax.swing.JLabel LBL_Name1;
    private javax.swing.JLabel LBL_Warning;
    private java.awt.List LST_Tendencias;
    private java.awt.ScrollPane PAN_Posts;
    private javax.swing.JPanel PNL_Pub;
    private javax.swing.JScrollPane SCR_Pub;
    private javax.swing.JScrollPane SCR_Pub1;
    private javax.swing.JTextPane TXT_Content;
    private javax.swing.JTextPane TXT_Content1;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
