/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1;

import java.awt.Image;
import java.io.File;
import java.sql.ResultSet;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSpinner;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Vicente193373
 */
public class VNT_Perfil extends javax.swing.JFrame {

    /**
     * Creates new form VNT_Inicio
     */
    File im;
    String Main_ID;
    String Show_ID;
    
    public VNT_Perfil() 
    {
        
        initComponents();
        
        System.out.println("\n   JFRAME 'VNT_Perfil' HAS BEEN INICIATED\n\n");
        System.out.println("   Main_ID = " + Main_ID + ", Show_ID = " + Show_ID);
        
        BTN_PConf.setVisible(false);
        TGL_Follow.setVisible(false);
        BTN_EBio.setText("🖉");
        BTN_EDate.setText("🖉");
        BTN_ELocat.setText("🖉");
        BTN_EName.setText("🖉");
        
        /*else
        {
            BTN_EBio.setVisible(false);
            BTN_EDate.setVisible(false);
            BTN_ELocat.setVisible(false);
            BTN_EName.setVisible(false);
        }//*/
    }

    //*/Esta funcion se encarga de recibir el id del usuario que inicio sesion y
    //tambien el prefil del usuario a ser mostrado
    public void recieveIDs(String variable, String variable1) 
    {
        this.Main_ID = variable;
        this.Show_ID = variable1;
        
        System.out.println("\n   Sesion " + Main_ID + " Iniciada \n\n");
        System.out.println("   Mostrando Perfil " + Show_ID + " \n\n");
            
        if(Main_ID != Show_ID)
        {
            BTN_EBio.setVisible(false);
            BTN_EDate.setVisible(false);
            BTN_ELocat.setVisible(false);
            BTN_EName.setVisible(false);
        }
        
        ProfileUpdate(Show_ID);
    }//*/
    
    
    public void ProfileUpdate(String Show_ID)
    {
        DB_con db_c = new DB_con();
        
        System.out.println("   Comprobando Perfil de " + db_c.Adyacent_Element("nombre", "Usuario", Show_ID, "id_usuario") + " \n\n");
        
        LBL_Titulo.setText("Perfil de " + db_c.Adyacent_Element("nombre", "Usuario", Show_ID, "id_usuario"));
        LBL_Nombre.setText(db_c.Adyacent_Element("nombre", "Usuario", Show_ID, "id_usuario"));
        LBL_Nombre2.setText(db_c.Adyacent_Element("id_usuario", "Usuario", Show_ID, "id_usuario"));
        BTN_Photo.setIcon(db_c.Prfl_Photo(Show_ID, BTN_Photo.getHeight(), BTN_Photo.getWidth()));
        LBL_Ubicacion.setText(db_c.Adyacent_Element("ubicacion", "Perfil", Show_ID, "id_usuario"));
        LBL_CDate.setText(db_c.Adyacent_Element("fecha_nacimiento", "Usuario", Show_ID, "id_usuario"));
        LBL_Following.setVisible(false);
        LBL_Followers.setVisible(false);
        TXT_Biography.setText(db_c.Adyacent_Element("biografia", "Perfil", Show_ID, "id_usuario"));
        
        if (Main_ID == Show_ID)
            LBL_Titulo.setText("Tu Perfil");
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        BTN_Inicio = new javax.swing.JButton();
        BTN_Explorar = new javax.swing.JButton();
        BTN_Notif = new javax.swing.JButton();
        BTN_Perfil = new javax.swing.JButton();
        BTN_Config = new javax.swing.JButton();
        FLD_Buscar = new javax.swing.JTextField();
        BTN_Buscar = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 50), new java.awt.Dimension(0, 50), new java.awt.Dimension(32767, 50));
        LST_Tendencias = new java.awt.List();
        BTN_Return = new javax.swing.JButton();
        LBL_Titulo = new javax.swing.JLabel();
        BTN_PConf = new javax.swing.JButton();
        LBL_Nombre = new javax.swing.JLabel();
        LBL_Ubicacion = new javax.swing.JLabel();
        LBL_Nombre2 = new javax.swing.JLabel();
        LBL_CDate = new javax.swing.JLabel();
        LBL_Following = new javax.swing.JLabel();
        LBL_Followers = new javax.swing.JLabel();
        BTN_Photo = new javax.swing.JButton();
        TGL_Follow = new javax.swing.JToggleButton();
        BTN_EBio = new javax.swing.JButton();
        BTN_EName = new javax.swing.JButton();
        BTN_EDate = new javax.swing.JButton();
        BTN_ELocat = new javax.swing.JButton();
        SPN_Biography = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        TXT_Biography = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        BTN_Inicio.setBackground(new java.awt.Color(30, 30, 30));
        BTN_Inicio.setFont(new java.awt.Font("Monospaced", 2, 24)); // NOI18N
        BTN_Inicio.setForeground(new java.awt.Color(255, 255, 255));
        BTN_Inicio.setText("Inicio");
        BTN_Inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_InicioActionPerformed(evt);
            }
        });

        BTN_Explorar.setBackground(new java.awt.Color(30, 30, 30));
        BTN_Explorar.setFont(new java.awt.Font("Monospaced", 2, 24)); // NOI18N
        BTN_Explorar.setForeground(new java.awt.Color(255, 255, 255));
        BTN_Explorar.setText("Explorar");
        BTN_Explorar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ExplorarActionPerformed(evt);
            }
        });

        BTN_Notif.setBackground(new java.awt.Color(30, 30, 30));
        BTN_Notif.setFont(new java.awt.Font("Monospaced", 2, 24)); // NOI18N
        BTN_Notif.setForeground(new java.awt.Color(255, 255, 255));
        BTN_Notif.setText("Notificaciones");
        BTN_Notif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_NotifActionPerformed(evt);
            }
        });

        BTN_Perfil.setBackground(new java.awt.Color(30, 30, 30));
        BTN_Perfil.setFont(new java.awt.Font("Monospaced", 3, 24)); // NOI18N
        BTN_Perfil.setForeground(new java.awt.Color(255, 255, 255));
        BTN_Perfil.setText("Perfil");
        BTN_Perfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_PerfilActionPerformed(evt);
            }
        });

        BTN_Config.setBackground(new java.awt.Color(30, 30, 30));
        BTN_Config.setFont(new java.awt.Font("Monospaced", 2, 24)); // NOI18N
        BTN_Config.setForeground(new java.awt.Color(255, 255, 255));
        BTN_Config.setText("Configuración");
        BTN_Config.setToolTipText("");
        BTN_Config.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ConfigActionPerformed(evt);
            }
        });

        BTN_Buscar.setText("Buscar");

        LST_Tendencias.setBackground(new java.awt.Color(30, 30, 30));
        LST_Tendencias.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        LST_Tendencias.setName("Tendencias"); // NOI18N

        BTN_Return.setFont(new java.awt.Font("Monospaced", 2, 24)); // NOI18N
        BTN_Return.setText("<");

        LBL_Titulo.setFont(new java.awt.Font("Monospaced", 2, 24)); // NOI18N
        LBL_Titulo.setText("Perfil de [NOMBRE_USUARIO]");

        BTN_PConf.setText("Configurar");
        BTN_PConf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_PConfActionPerformed(evt);
            }
        });

        LBL_Nombre.setFont(new java.awt.Font("Monospaced", 2, 24)); // NOI18N
        LBL_Nombre.setText("[NOMBRE_USUARIO]");

        LBL_Ubicacion.setFont(new java.awt.Font("Monospaced", 2, 14)); // NOI18N
        LBL_Ubicacion.setForeground(new java.awt.Color(153, 153, 153));
        LBL_Ubicacion.setText("[UBICACION]");

        LBL_Nombre2.setFont(new java.awt.Font("Monospaced", 2, 14)); // NOI18N
        LBL_Nombre2.setForeground(new java.awt.Color(153, 153, 153));
        LBL_Nombre2.setText("@[CUENTA_USUARIO]");

        LBL_CDate.setFont(new java.awt.Font("Monospaced", 2, 14)); // NOI18N
        LBL_CDate.setForeground(new java.awt.Color(153, 153, 153));
        LBL_CDate.setText("[FECHA_NACIMIENTO]");

        LBL_Following.setFont(new java.awt.Font("Monospaced", 2, 14)); // NOI18N
        LBL_Following.setForeground(new java.awt.Color(153, 153, 153));
        LBL_Following.setText("# Siguiendo");

        LBL_Followers.setFont(new java.awt.Font("Monospaced", 2, 14)); // NOI18N
        LBL_Followers.setForeground(new java.awt.Color(153, 153, 153));
        LBL_Followers.setText("# Seguidores");

        BTN_Photo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_PhotoActionPerformed(evt);
            }
        });

        TGL_Follow.setText("Seguir");
        TGL_Follow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TGL_FollowActionPerformed(evt);
            }
        });

        BTN_EBio.setFont(new java.awt.Font("Noto Sans", 0, 10)); // NOI18N
        BTN_EBio.setText("🖉");
        BTN_EBio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_EBioActionPerformed(evt);
            }
        });

        BTN_EName.setFont(new java.awt.Font("Noto Sans", 0, 12)); // NOI18N
        BTN_EName.setText("🖉");
        BTN_EName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ENameActionPerformed(evt);
            }
        });

        BTN_EDate.setFont(new java.awt.Font("Noto Sans", 0, 10)); // NOI18N
        BTN_EDate.setText("🖉");
        BTN_EDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_EDateActionPerformed(evt);
            }
        });

        BTN_ELocat.setFont(new java.awt.Font("Noto Sans", 0, 10)); // NOI18N
        BTN_ELocat.setText("🖉");
        BTN_ELocat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ELocatActionPerformed(evt);
            }
        });

        TXT_Biography.setEditable(false);
        TXT_Biography.setColumns(20);
        TXT_Biography.setLineWrap(true);
        TXT_Biography.setRows(5);
        TXT_Biography.setText("[BIOGRAFIA]");
        TXT_Biography.setWrapStyleWord(true);
        jScrollPane2.setViewportView(TXT_Biography);

        SPN_Biography.setViewportView(jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BTN_Notif)
                    .addComponent(BTN_Perfil, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTN_Config, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTN_Inicio, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTN_Explorar, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(12, 12, 12)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BTN_ELocat, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LBL_Ubicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTN_EDate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LBL_CDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BTN_Photo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(LBL_Following, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LBL_Followers, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 26, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TGL_Follow, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(BTN_PConf)
                                .addGap(46, 46, 46))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LBL_Nombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LBL_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BTN_EName)))
                                .addGap(5, 5, 5))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BTN_Return, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LBL_Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(SPN_Biography)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BTN_EBio, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BTN_Buscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FLD_Buscar))
                    .addComponent(LST_Tendencias, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN_Buscar)
                    .addComponent(FLD_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LST_Tendencias, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator2))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(BTN_Inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BTN_Explorar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BTN_Notif, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BTN_Perfil, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BTN_Config, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BTN_Return, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LBL_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(LBL_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BTN_EName, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LBL_Nombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BTN_PConf)
                                    .addComponent(TGL_Follow, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(LBL_Following, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LBL_Followers, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(BTN_Photo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LBL_CDate, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTN_EDate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTN_ELocat, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LBL_Ubicacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(SPN_Biography, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTN_EBio, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(217, 217, 217))))
        );

        BTN_Inicio.getAccessibleContext().setAccessibleName("ID_BTN_Inicio");
        BTN_Explorar.getAccessibleContext().setAccessibleName("ID_BTN_Buscar");
        BTN_Notif.getAccessibleContext().setAccessibleName("ID_BTN_Notif");
        BTN_Perfil.getAccessibleContext().setAccessibleName("ID_BTN_Perfil");
        BTN_Config.getAccessibleContext().setAccessibleName("ID_BTN_Config");
        FLD_Buscar.getAccessibleContext().setAccessibleName("ID_FLD_Publicar");
        BTN_Buscar.getAccessibleContext().setAccessibleName("ID_BTN_Buscar");
        LST_Tendencias.getAccessibleContext().setAccessibleName("ID_LST_Tendencias");
        BTN_Return.getAccessibleContext().setAccessibleName("ID_BTN_Return");
        LBL_Titulo.getAccessibleContext().setAccessibleName("ID_LBL_Titulo");
        BTN_PConf.getAccessibleContext().setAccessibleName("ID_BTN_CPerfil");
        LBL_Nombre.getAccessibleContext().setAccessibleName("ID_LBL_Nombre");
        LBL_Ubicacion.getAccessibleContext().setAccessibleName("ID_LBL_Ubicacion");
        LBL_CDate.getAccessibleContext().setAccessibleName("ID_LBL_CDate");
        LBL_Following.getAccessibleContext().setAccessibleName("ID_LBL_Siguiendo");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_InicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_InicioActionPerformed
        // TODO add your handling code here:
        VNT_Inicio NewVI = new VNT_Inicio();
        
        System.out.println("\n   Comprobando Sesion " + Main_ID + "... \n\n");
        
        //Se pasa el ID_del usuario que inicio sesion
        NewVI.recieveID(Main_ID);
        
        //Se hace visible a la ventana de inicio
        NewVI.setVisible(true);
        
        //Se hace invisible y se desaparece la ventana de login actual
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_BTN_InicioActionPerformed

    private void BTN_ExplorarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ExplorarActionPerformed
        // TODO add your handling code here:
        VNT_Explorar NewVE = new VNT_Explorar();
        NewVE.recieveID(Main_ID);
        NewVE.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_BTN_ExplorarActionPerformed

    private void BTN_NotifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_NotifActionPerformed
        // TODO add your handling code here:
        VNT_Notif NewVN = new VNT_Notif();
        NewVN.recieveID(Main_ID);
        NewVN.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_BTN_NotifActionPerformed

    private void BTN_PerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_PerfilActionPerformed
        // TODO add your handling code here:
        VNT_Perfil NewVP = new VNT_Perfil();
        System.out.println("\n   " + Main_ID + " Transportado \n\n");
        NewVP.recieveIDs(Main_ID, Main_ID);
        NewVP.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_BTN_PerfilActionPerformed

    private void BTN_ConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ConfigActionPerformed
        // TODO add your handling code here:
        VNT_Configuracion NewVCn = new VNT_Configuracion();
        NewVCn.recieveID(Main_ID);
        NewVCn.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_BTN_ConfigActionPerformed

    private void BTN_PhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_PhotoActionPerformed
        // TODO add your handling code here:
        DB_con db_c = new DB_con();
        
        //Se debe definir para usar la ventanilla que busca un archivo
        JFileChooser archivo = new JFileChooser();
        archivo.showOpenDialog(this);
        this.im = archivo.getSelectedFile();
        
        //Se guarda en 'path' la ubicacion del archivo elegido que sera la foto de perfil
        String path_img = this.im.getAbsolutePath();
        
        //Se toma la imagen y se define como un icono asignable
        ImageIcon img = new ImageIcon(new ImageIcon(path_img).getImage().getScaledInstance(BTN_Photo.getHeight(), BTN_Photo.getWidth(), Image.SCALE_DEFAULT));
        this.BTN_Photo.setIcon(img);
        
        //Se actualiza la foto en la base de datos
        db_c.Update_Photo(Main_ID, path_img);
        ProfileUpdate(Show_ID);
    }//GEN-LAST:event_BTN_PhotoActionPerformed

    private void TGL_FollowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TGL_FollowActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TGL_FollowActionPerformed

    private void BTN_PConfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_PConfActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_BTN_PConfActionPerformed

    private void BTN_ENameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ENameActionPerformed
        // TODO add your handling code here:
        String NewName = JOptionPane.showInputDialog(null, "Introduce el nuevo nombre:");
        
        if (NewName != null && !NewName.trim().isEmpty())
        {
            //Se define la conexion usando el archivo predefinido DB_con.java
            DB_con db_c = new DB_con();
            db_c.Update_String("id_usuario", Main_ID, "Usuario", "nombre", NewName);
            System.out.println("\n   Nuevo Nombre de " + Main_ID + ": " + NewName + "\n\n");
            ProfileUpdate(Show_ID);
        }
        else
        {
            System.out.println("\n   Asignacion de Nuevo Nombre Cancelada \n\n");
        }
    }//GEN-LAST:event_BTN_ENameActionPerformed

    private void BTN_ELocatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ELocatActionPerformed
        // TODO add your handling code here:
        String NewLocal = JOptionPane.showInputDialog(null, "Introduce la nueva ubicación:");
        
        if (NewLocal != null && !NewLocal.trim().isEmpty())
        {
            //Se define la conexion usando el archivo predefinido DB_con.java
            DB_con db_c = new DB_con();
            
            db_c.Update_String("id_usuario", Main_ID, "Usuario", "pais", NewLocal);
            db_c.Update_String("id_usuario", Main_ID, "Perfil", "ubicacion", NewLocal);
            System.out.println("\n   Nueva Ubicación de " + Main_ID + ": " + NewLocal + "\n\n");
            
            ProfileUpdate(Show_ID);
        }
        else
        {
            System.out.println("\n   Asignacion de Nueva Ubicación Cancelada \n\n");
        }
    }//GEN-LAST:event_BTN_ELocatActionPerformed

    private void BTN_EBioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_EBioActionPerformed
        // TODO add your handling code here:
        /*
        String NewBio = JOptionPane.showInputDialog(null, "Introduce la nueva Biografía:");
        
        if (NewBio != null && !NewBio.trim().isEmpty())
        {
            //Se define la conexion usando el archivo predefinido DB_con.java
            DB_con db_c = new DB_con();
            db_c.Update_String("id_usuario", Main_ID, "Perfil", "biografia", NewBio);
            System.out.println("\n   Nueva Biografía de " + Main_ID + ":\n   " + NewBio + "\n\n");
            ProfileUpdate(Show_ID);
        }
        else
        {
            System.out.println("\n   Asignacion de Nueva Ubicación Cancelada \n\n");
        }*/
        
        JTextArea campoTexto = new JTextArea(5, 30); //5 filas, 30 columnas
        campoTexto.setLineWrap(true);
        campoTexto.setWrapStyleWord(true);
        
        JScrollPane scroll = new JScrollPane(campoTexto);

        int result = JOptionPane.showConfirmDialog(null, scroll, "Introduce Nueva Biografía", JOptionPane.OK_CANCEL_OPTION);

        if (result == JOptionPane.OK_OPTION)
        {
            //Se define la conexion usando el archivo predefinido DB_con.java
            DB_con db_c = new DB_con();
            
            String NewBio = campoTexto.getText();
            db_c.Update_String("id_usuario", Main_ID, "Perfil", "biografia", NewBio);
            System.out.println("\n   Nueva Biografía de " + Main_ID + ": \n    " + NewBio + "\n\n");
            
            ProfileUpdate(Show_ID);
        }
        else
        {
            System.out.println("\n   Asignacion de Nueva Biografía Cancelada \n\n");
        }
    }//GEN-LAST:event_BTN_EBioActionPerformed

    private void BTN_EDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_EDateActionPerformed
        // TODO add your handling code here:
        JSpinner D = new JSpinner(new SpinnerNumberModel(1, 1, 31, 1));
        JSpinner M = new JSpinner(new SpinnerNumberModel(1, 1, 12, 1));
        JSpinner Y = new JSpinner(new SpinnerNumberModel(1900, 1000, 3000, 1));

        JPanel panel = new JPanel();
        
        panel.add(new JLabel("Dia:"));
        panel.add(D);
        
        panel.add(new JLabel(" Mes:"));
        panel.add(M);
        
        panel.add(new JLabel(" Año:"));
        panel.add(Y);

        int result = JOptionPane.showConfirmDialog(null, panel, "Nueva Fecha de Nacimiento", JOptionPane.OK_CANCEL_OPTION);

        if (result == JOptionPane.OK_OPTION) 
        {
            //Se define la conexion usando el archivo predefinido DB_con.java
            DB_con db_c = new DB_con();
            
            int Day = (int) D.getValue();
            int Month = (int) M.getValue();
            int Year = (int) Y.getValue();
            
            //Se procesan los valores en el formato adecuado para una fecha en SQL
            LocalDate bdate = LocalDate.of(Year, Month, Day);
            DateTimeFormatter formato = DateTimeFormatter.ofPattern("yyyy-MM-dd");
            
            //Se guarda en 'birth' lo que se intordujo como fecha de nacimiento
            String NewBirth = bdate.format(formato);
            db_c.Update_String("id_usuario", Main_ID, "Usuario", "fecha_nacimiento", NewBirth);
            
            System.out.println("\n   Nueva Fecha de Nacmiento de " + Main_ID + ": " + NewBirth);
            
            ProfileUpdate(Show_ID);
        }
        else
        {
            System.out.println("\n   Asignacion de Nueva Fecha de Nacimeinto Cancelada \n\n");
        }
    }//GEN-LAST:event_BTN_EDateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VNT_Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VNT_Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VNT_Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VNT_Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            public void run() 
            {
                new VNT_Perfil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_Buscar;
    private javax.swing.JButton BTN_Config;
    private javax.swing.JButton BTN_EBio;
    private javax.swing.JButton BTN_EDate;
    private javax.swing.JButton BTN_ELocat;
    private javax.swing.JButton BTN_EName;
    private javax.swing.JButton BTN_Explorar;
    private javax.swing.JButton BTN_Inicio;
    private javax.swing.JButton BTN_Notif;
    private javax.swing.JButton BTN_PConf;
    private javax.swing.JButton BTN_Perfil;
    private javax.swing.JButton BTN_Photo;
    private javax.swing.JButton BTN_Return;
    private javax.swing.JTextField FLD_Buscar;
    private javax.swing.JLabel LBL_CDate;
    private javax.swing.JLabel LBL_Followers;
    private javax.swing.JLabel LBL_Following;
    private javax.swing.JLabel LBL_Nombre;
    private javax.swing.JLabel LBL_Nombre2;
    private javax.swing.JLabel LBL_Titulo;
    private javax.swing.JLabel LBL_Ubicacion;
    private java.awt.List LST_Tendencias;
    private javax.swing.JScrollPane SPN_Biography;
    private javax.swing.JToggleButton TGL_Follow;
    private javax.swing.JTextArea TXT_Biography;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
